### PR TITLE
OpenSea page

### PR DESCRIPTION
**Pull request by nathanjessen**
Resubmitting PR #2 

First iteration of an OpenSea page which pulls assets from OpenSea.
Future improvements will allow for viewing NFT details and buying directly from the app.

Testing, I added this to my .env.local to pull assets from an account with many NFTs available

```REACT_APP_OPENSEA_ADDRESS=0x6e7cacc6f2b49dfb980663bf2bb014046ac45320```

Additional needs:
Request an API key from OpenSea and add this to the .env file
https://docs.opensea.io/reference#request-an-api-key

Empty list
Screenshot from 2020-10-11 23-27-40

NFTs available
Screenshot from 2020-10-11 23-22-53

### CODE REVIEW

**Comment by nathanjessen** [comment]
I haven't looked into using the dark theme on this page yet, so that might be something someone else could tackle.

**Comment by octofi** [comment]
Thanks Nathan, you are the best. I will test now locally and add our opensea marketplace with the next update.

**Comment by octofi** [comment]
just requested API Key and waiting now

**Comment by nathanjessen** [comment]
Dark theme is fixed.
Renamed to NFT.
Removed the Overview cards to simplify page layout and keep it consistent with other pages.

nft-dark

**Pull request closed without merging**
